export const ASSETS = {
  tilesets: {
    classroom: "/game/assets/tilesets/classroom_interior.png",
  },
  sprites: {
    player: "/game/assets/sprites/muridmc.png",
    guru: "/game/assets/sprites/guru.png",
    murid: "/game/assets/sprites/murid.png",
    murid1: "/game/assets/sprites/murid1.png",
    murid2: "/game/assets/sprites/murid2.png",
    murid3: "/game/assets/sprites/murid3.png",
    murid4: "/game/assets/sprites/murid4.png",
    muridmc: "/game/assets/sprites/muridmc.png",
    timsar: "/game/assets/sprites/timsar.png",
    prof: "/game/assets/sprites/prof.png",
  },
  ui: {
    dialogBox: "/game/assets/ui/dialog_box.png",
  },
  effects: {
    earthquake: "/game/assets/effects/earthquake_effect.png",
    sandstorm: "/game/assets/effects/sandstorm_tile.png",
  },
  comics: {
    comic1: "/game/assets/comics/comic1.png",
    comic2: "/game/assets/comics/comic2.png",
    comic3: "/game/assets/comics/comic3.png",
    comic4: "/game/assets/comics/comic4.png",
    comic5: "/game/assets/comics/comic5.png",
    comic6: "/game/assets/comics/comic6.png",
    comic7: "/game/assets/comics/comic7.png",
    comic8: "/game/assets/comics/comic8.png",
    comic9: "/game/assets/comics/comic9.png",
  },
  audio: {
    quake: "/game/assets/audio/quake.wav",
  },
  objects: {
    floorTile: "/game/assets/objects/classroom/floor_tile.png",
    wallTile: "/game/assets/objects/classroom/wall_tile.png",
    wallFront: "/game/assets/objects/classroom/wall_front.png",
    wallBorder: "/game/assets/objects/classroom/wall_border.png",
    chalkboard: "/game/assets/objects/classroom/chalkboard.png",
    chalkboard_hazard: "/game/assets/objects/classroom/chalkboard_hazard.png",
    window: "/game/assets/objects/classroom/window.png",
    window_hazard: "/game/assets/objects/classroom/window_hazard.png",
    door: "/game/assets/objects/classroom/door.png",
    desk: "/game/assets/objects/classroom/desk.png",
    chair: "/game/assets/objects/classroom/chair.png",
    chair_hazard: "/game/assets/objects/classroom/chair_hazard.png",
    teacherDesk: "/game/assets/objects/classroom/teacher_desk.png",
    teacher_desk_hazard: "/game/assets/objects/classroom/teacher_desk_hazard.png",
    cabinet: "/game/assets/objects/classroom/cabinet.png",
    cabinet_hazard: "/game/assets/objects/classroom/cabinet_hazard.png",
    cupboard: "/game/assets/objects/classroom/cupboard.png",
    cupboard_hazard: "/game/assets/objects/classroom/cupboard_hazard.png",
    bookshelf: "/game/assets/objects/classroom/bookshelf.png",
    bookshelf_hazard: "/game/assets/objects/classroom/bookshelf_hazard.png",
    poster: "/game/assets/objects/classroom/poster.png",
    map: "/game/assets/objects/classroom/map.png",
    mading: "/game/assets/objects/classroom/mading.png",
    plant: "/game/assets/objects/classroom/plant.png",
    plant_hazard: "/game/assets/objects/classroom/plant_hazard.png",
    trashBin: "/game/assets/objects/classroom/trash_bin.png",
    trash_bin_hazard: "/game/assets/objects/classroom/trash_bin_hazard.png",
    bigTrash: "/game/assets/objects/classroom/bigtrash.png",
    medic: "/game/assets/objects/classroom/medic.png",
    alarm: "/game/assets/objects/classroom/alarm.png",
    pemadam: "/game/assets/objects/classroom/pemadam.png",
    debris: "/game/assets/objects/classroom/debris.png",
    debris1: "/game/assets/objects/classroom/debris_1.png",
    debris2: "/game/assets/objects/classroom/debris_2.png",
    debris3: "/game/assets/objects/classroom/debris_3.png",
    debris4: "/game/assets/objects/classroom/debris_4.png",
    crack: "/game/assets/objects/classroom/crack.png",
    warningIcon: "/game/assets/objects/classroom/warning_icon.png",
    safeMarker: "/game/assets/objects/classroom/safe_marker.png",
    exitMarker: "/game/assets/objects/classroom/exit_marker.png",
    autoContactSheet: "/game/assets/objects/auto_contact_sheet.png",
    tileContactSheet: "/game/assets/objects/tile_contact_sheet.png",
    cropReport: "/game/assets/objects/crop_report.json",
  },
};
