import { zoneImages } from "./eduquakeAssets";
import { npcs } from "./npcs";

export const journeyZones = [
  {
    id: "command-center",
    order: 0,
    name: "Command Center Hub",
    shortName: "Command",
    biome: "Advanced command room",
    image: zoneImages.commandCenter,
    npc: npcs.professorQuake,
    map: { x: 50, y: 9 },
    mission: "Masuk ke hub dan mulai perjalanan kesiapsiagaan.",
    tip: "Progress tersimpan otomatis di browser perangkat ini.",
    objectives: ["Cek level", "Pilih Start Journey", "Lihat rute belajar"],
    discovery: "Save Terminal",
    rewards: { xp: 40, coins: 2 },
  },
  {
    id: "earthquake-basics",
    order: 1,
    name: "Earthquake Basics",
    shortName: "Basics",
    biome: "Pixel classroom",
    image: zoneImages.classroom,
    npc: npcs.professorQuake,
    map: { x: 50, y: 23 },
    mission: "Pelajari dasar gempa dan prinsip Drop, Cover, Hold.",
    tip: "Saat guncangan kuat, lindungi kepala sebelum bergerak keluar.",
    objectives: ["Buka chalkboard", "Aktifkan seismic globe", "Temukan knowledge book"],
    discovery: "Knowledge Book",
    rewards: { xp: 120, coins: 8 },
  },
  {
    id: "risk-map",
    order: 2,
    name: "Yogyakarta Risk Map",
    shortName: "Risk Map",
    biome: "Regional map route",
    image: zoneImages.riskMap,
    npc: npcs.citizen,
    map: { x: 35, y: 39 },
    mission: "Identifikasi zona risiko lokal Yogyakarta.",
    tip: "Risiko dibaca dari tanah, struktur, rute, dan kebiasaan warga.",
    objectives: ["Pilih Bantul", "Pilih Sleman", "Pilih Gunungkidul"],
    discovery: "Historical Sign",
    rewards: { xp: 140, coins: 10 },
  },
  {
    id: "home-mitigation",
    order: 3,
    name: "Home Mitigation",
    shortName: "Home Safety",
    biome: "House inspection room",
    image: zoneImages.homeSafety,
    npc: npcs.emergencyRanger,
    map: { x: 65, y: 39 },
    mission: "Inspeksi rumah dan amankan bahaya utama.",
    tip: "Rak tinggi, kaca, gas, dan jalur keluar adalah prioritas inspeksi.",
    objectives: ["Amankan furnitur", "Tandai titik aman", "Bersihkan jalur keluar"],
    discovery: "Preparedness Bonus",
    rewards: { xp: 150, coins: 10 },
  },
  {
    id: "emergency-kit",
    order: 4,
    name: "Emergency Kit",
    shortName: "Kit",
    biome: "Preparedness inventory room",
    image: zoneImages.inventoryRoom,
    npc: npcs.emergencyRanger,
    map: { x: 50, y: 55 },
    mission: "Masukkan suplai penting ke tas siaga.",
    tip: "Air, makanan, P3K, senter, radio, dan dokumen adalah inti awal.",
    objectives: ["Kumpulkan item", "Validasi tas siaga", "Dapatkan badge inventory"],
    discovery: "Secret Supply Cache",
    rewards: { xp: 170, coins: 12 },
  },
  {
    id: "simulation",
    order: 5,
    name: "Earthquake Simulation",
    shortName: "Simulation",
    biome: "Emergency shaking room",
    image: zoneImages.shakingRoom,
    npc: npcs.rescueCommander,
    map: { x: 34, y: 71 },
    mission: "Latih reaksi cepat saat ruangan mulai berguncang.",
    tip: "Urutan aman: Drop, Cover, Hold, lalu evaluasi jalur.",
    objectives: ["Mulai timer", "Pilih aksi benar", "Selesaikan siren drill"],
    discovery: "Emergency Story",
    rewards: { xp: 190, coins: 14 },
  },
  {
    id: "evacuation",
    order: 6,
    name: "Evacuation & Survival",
    shortName: "Evacuation",
    biome: "Route to safe shelter",
    image: zoneImages.evacuationRoute,
    npc: npcs.rescueCommander,
    map: { x: 66, y: 71 },
    mission: "Ikuti rambu evakuasi dan hindari jalur berbahaya.",
    tip: "Jangan kembali masuk sebelum ada instruksi aman.",
    objectives: ["Pilih rambu aman", "Hindari kabel/kaca", "Capai shelter"],
    discovery: "Shelter Marker",
    rewards: { xp: 190, coins: 14 },
  },
  {
    id: "final-challenge",
    order: 7,
    name: "Final Preparedness Test",
    shortName: "Final",
    biome: "Advanced command HQ",
    image: zoneImages.advancedHq,
    npc: npcs.professorQuake,
    map: { x: 50, y: 87 },
    mission: "Buktikan kesiapsiagaan dan klaim badge akhir.",
    tip: "Jawaban final menguji konsep dari seluruh zona sebelumnya.",
    objectives: ["Jawab kuis", "Cek skor", "Klaim completion badge"],
    discovery: "Completion Badge",
    rewards: { xp: 220, coins: 20 },
  },
];

export const zoneById = Object.fromEntries(journeyZones.map((zone) => [zone.id, zone]));
